### ISSUE TITLE
celldex::BlueprintEncodeData() Failed to collect lazy table caused by error in db_collec()

### ISSUE THREAD

**Issue by catinogen** [yerkes-gencore/scRNAseqWorkshop2023#95]
It seems like a recent compatibility issue with the newest version of dplyr...

https://support.bioconductor.org/p/9154865/

**Comment by derrik-gratz** [comment]
Thanks for posting this and sorry for not getting to it earlier. I tried installing the github version of the package only via `remotes::install_github('Bioconductor/BiocFileCache', ref = 'devel')`, but this did not fix the issue. Only upgrading to BioConductor version 3.18 via `BiocManager::install('BiocFileCache', version = 3.18)` fixed the issue. There may be other dependencies besides BiocFileCache that needed to be updated too.

**Comment by catinogen** [comment]
Okay! Thank you very much.
